//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seismic_Acquisition.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Acquire_EW_Maximum {
            get {
                return ((int)(this["Acquire_EW_Maximum"]));
            }
            set {
                this["Acquire_EW_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000")]
        public int Acquire_EW_Minimum {
            get {
                return ((int)(this["Acquire_EW_Minimum"]));
            }
            set {
                this["Acquire_EW_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Acquire_NS_Maximum {
            get {
                return ((int)(this["Acquire_NS_Maximum"]));
            }
            set {
                this["Acquire_NS_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000")]
        public int Acquire_NS_Minimum {
            get {
                return ((int)(this["Acquire_NS_Minimum"]));
            }
            set {
                this["Acquire_NS_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int History_EW_Maximum {
            get {
                return ((int)(this["History_EW_Maximum"]));
            }
            set {
                this["History_EW_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000")]
        public int History_EW_Minimum {
            get {
                return ((int)(this["History_EW_Minimum"]));
            }
            set {
                this["History_EW_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int History_NS_Maximum {
            get {
                return ((int)(this["History_NS_Maximum"]));
            }
            set {
                this["History_NS_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000")]
        public int History_NS_Minimum {
            get {
                return ((int)(this["History_NS_Minimum"]));
            }
            set {
                this["History_NS_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double Acquire_EW_Up {
            get {
                return ((double)(this["Acquire_EW_Up"]));
            }
            set {
                this["Acquire_EW_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double Acquire_EW_Down {
            get {
                return ((double)(this["Acquire_EW_Down"]));
            }
            set {
                this["Acquire_EW_Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double Acquire_NS_Up {
            get {
                return ((double)(this["Acquire_NS_Up"]));
            }
            set {
                this["Acquire_NS_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double Acquire_NS_Down {
            get {
                return ((double)(this["Acquire_NS_Down"]));
            }
            set {
                this["Acquire_NS_Down"] = value;
            }
        }
    }
}
